const Data = {
  title: 'SDMX',
  language: ['Fr', 'En'],
  list: [
    {
      id: 0,
      Name: 'VTT Tout Suspendu 26\'\' Bliss Noir Orange Freins à Disques 21 Vit TC 47 cm 532M',
      Prix: 1763.00,
      Image: 'http://www.cyclesduloir.com/media/g_vignette/118312',
      Categories: 'sport',
      Type: [
        'Vélo tout terrain',
        'Vélo pliable',
      ],
      Marque: 'SCOTT',
      Vente: 'enchère',
    },
    {
      id: 1,
      Name: 'Vélo BMX 20\'\' Freestyle KS cycling G-surge, rotor 360° - NEUF',
      Prix: 900.00,
      Image: 'https://www.decathlon.fr/media/834/8343668/big_9c4a3fe98ffc40538619ed177c8b15ea.jpg',
      Categories: 'sport',
      Type: [
        'Vélo BMX',
        'Vélo tout terrain',
      ],
      Marque: 'GT',
      Vente: 'achat immédiat',
    },
    {
      id: 2,
      Name: 'Viking Omnium 1.0 Gents 700 14 Vitesse Road Racing Bike vélo 3 tailles noir',
      Prix: 201.00,
      Image: 'https://static.cyclelab.eu/velos/scott/2007/highres/249692.jpg',
      Categories: 'sport',
      Type: [
        'Vélo de route',
        'Vélo tout terrain',
      ],
      Marque: 'GT',
      Vente: 'enchère',
    },
    {
      id: 3,
      Name: 'VTT 26\'\' KS Cycling Slyder tout suspendu 21 vitesses, TC 51 cm - NEUF',
      Prix: 179.00,
      Image: 'https://www.topvelo.fr/documents/Image/different-type-vtt-2.jpg',
      Categories: 'sport',
      Type: [
        'Vélo tout terrain',
      ],
      Marque: 'DECATHLON',
      Vente: 'achat immédiat',
    },
    {
      id: 4,
      Name: 'Viking Omnium 1.0 Gents 700 14 Vitesse Road Racing Bike vélo 3 tailles noir',
      Prix: 201.00,
      Image: 'https://static.cyclelab.eu/velos/scott/2007/highres/249692.jpg',
      Categories: 'sport',
      Type: [
        'Vélo de route',
        'Vélo tout terrain',
      ],
      Marque: 'GT',
      Vente: 'enchère',
    },
    {
      id: 5,
      Name: 'Vélo BMX 20\'\' Freestyle KS cycling G-surge, rotor 360° - NEUF',
      Prix: 900.00,
      Image: 'https://www.decathlon.fr/media/834/8343668/big_9c4a3fe98ffc40538619ed177c8b15ea.jpg',
      Categories: 'sport',
      Type: [
        'Vélo BMX',
        'Vélo tout terrain',
      ],
      Marque: 'GT',
      Vente: 'enchère',
    },
    {
      id: 6,
      Name: 'Viking Omnium 1.0 Gents 700 14 Vitesse Road Racing Bike vélo 3 tailles noir',
      Prix: 201.00,
      Image: 'https://static.cyclelab.eu/velos/scott/2007/highres/249692.jpg',
      Categories: 'sport',
      Type: [
        'Vélo de route',
        'Vélo tout terrain',
      ],
      Marque: 'GT',
      Vente: 'achat immédiat',
    },
    {
      id: 7,
      Name: 'VTT Tout Suspendu 26\'\' Bliss Noir Orange Freins à Disques 21 Vit TC 47 cm 532M',
      Prix: 1763.00,
      Image: 'http://www.cyclesduloir.com/media/g_vignette/118312',
      Categories: 'sport',
      Type: [
        'Vélo tout terrain',
        'Vélo pliable',
      ],
      Marque: 'SCOTT',
      Vente: 'achat immédiat',
    },
    {
      id: 8,
      Name: 'Vélo BMX 20\'\' Freestyle KS cycling G-surge, rotor 360° - NEUF',
      Prix: 900.00,
      Image: 'https://www.decathlon.fr/media/834/8343668/big_9c4a3fe98ffc40538619ed177c8b15ea.jpg',
      Categories: 'sport',
      Type: [
        'Vélo BMX',
        'Vélo tout terrain',
      ],
      Marque: 'GT',
      Vente: 'enchère',
    },
    {
      id: 9,
      Name: 'Viking Omnium 1.0 Gents 700 14 Vitesse Road Racing Bike vélo 3 tailles noir',
      Prix: 201.00,
      Image: 'https://static.cyclelab.eu/velos/scott/2007/highres/249692.jpg',
      Categories: 'sport',
      Type: [
        'Vélo de route',
        'Vélo tout terrain',
      ],
      Marque: 'GT',
      Vente: 'enchère',
    },
    {
      id: 10,
      Name: 'VTT 26\'\' KS Cycling Slyder tout suspendu 21 vitesses, TC 51 cm - NEUF',
      Prix: 179.00,
      Image: 'https://www.topvelo.fr/documents/Image/different-type-vtt-2.jpg',
      Categories: 'sport',
      Type: [
        'Vélo tout terrain',
      ],
      Marque: 'DECATHLON',
      Vente: 'enchère',
    },
    {
      id: 11,
      Name: 'Viking Omnium 1.0 Gents 700 14 Vitesse Road Racing Bike vélo 3 tailles noir',
      Prix: 201.00,
      Image: 'https://static.cyclelab.eu/velos/scott/2007/highres/249692.jpg',
      Categories: 'sport',
      Type: [
        'Vélo de route',
        'Vélo tout terrain',
      ],
      Marque: 'GT',
      Vente: 'enchère',
    },
    {
      id: 12,
      Name: 'Vélo BMX 20\'\' Freestyle KS cycling G-surge, rotor 360° - NEUF',
      Prix: 900.00,
      Image: 'https://www.decathlon.fr/media/834/8343668/big_9c4a3fe98ffc40538619ed177c8b15ea.jpg',
      Categories: 'sport',
      Type: [
        'Vélo BMX',
        'Vélo tout terrain',
      ],
      Marque: 'GT',
      Vente: 'enchère',
    },
    {
      id: 13,
      Name: 'Viking Omnium 1.0 Gents 700 14 Vitesse Road Racing Bike vélo 3 tailles noir',
      Prix: 201.00,
      Image: 'https://static.cyclelab.eu/velos/scott/2007/highres/249692.jpg',
      Categories: 'sport',
      Type: [
        'Vélo de route',
        'Vélo tout terrain',
      ],
      Marque: 'GT',
      Vente: 'achat immédiat',
    },
  ],
  facetedbox: [
    {
      id: 0,
      name: 'Categories',
      facets: ['Tout', 'Sports, vacances', 'Autres', 'Camping, randonnée'],
    },
  ],
  filterbox: [
    {
      id: 0,
      name: 'Type',
      filtres: ['Vélo BMX', 'Vélo de route', 'Vélo électrique', 'Vélo pliable', 'Vélo tout terrain'],
    },
    {
      id: 1,
      name: 'Marque',
      filtres: ['DECATHLON', 'SCOTT', 'SPECIALIZED', 'GT'],
    },
  ],
};

export default Data;
